---
abstract: 'DBIx::Class::Schema Model Class'
author:
  - 'Brandon L Black C<blblack at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-DBIC-Schema
no_index:
  directory:
    - inc
    - t
provides:
  Catalyst::Helper::Model::DBIC::Schema:
    file: lib/Catalyst/Helper/Model/DBIC/Schema.pm
    version: 0.39
  Catalyst::Model::DBIC::Schema:
    file: lib/Catalyst/Model/DBIC/Schema.pm
    version: 0.39
  Catalyst::TraitFor::Model::DBIC::Schema::Caching:
    file: lib/Catalyst/TraitFor/Model/DBIC/Schema/Caching.pm
  Catalyst::TraitFor::Model::DBIC::Schema::Replicated:
    file: lib/Catalyst/TraitFor/Model/DBIC/Schema/Replicated.pm
  Catalyst::TraitFor::Model::DBIC::Schema::SchemaProxy:
    file: lib/Catalyst/TraitFor/Model/DBIC/Schema/SchemaProxy.pm
requires:
  Carp::Clan: 0
  Catalyst::Runtime: 5.80005
  CatalystX::Component::Traits: 0.14
  DBIx::Class: 0.08114
  List::MoreUtils: 0
  Moose: 0
  MooseX::Types: 0
  Tie::IxHash: 0
  namespace::autoclean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Model-DBIC-Schema/
version: 0.39
