---
name: Catalyst-Model-DBIC-Schema
version: 0.16
author:
  - 'Brandon L Black, C<blblack@gmail.com>'
abstract: DBIx::Class::Schema Model Class
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.64
  Class::Accessor::Fast: 0.22
  Class::Data::Accessor: 0.02
  DBIx::Class: 0.06
  UNIVERSAL::require: 0.1
build_requires:
  Test::More: 0.32
recommends:
  DBIx::Class::Schema::Loader: 0.03003
provides:
  Catalyst::Helper::Model::DBIC::Schema:
    file: lib/Catalyst/Helper/Model/DBIC/Schema.pm
  Catalyst::Model::DBIC::Schema:
    file: lib/Catalyst/Model/DBIC/Schema.pm
    version: 0.16
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
