---
name: Catalyst-Model-DBIC-Schema
version: 0.08
author:
  - 'Brandon L Black, C<blblack@gmail.com>'
abstract: DBIx::Class::Schema Model Class
license: perl
requires:
  Catalyst: 5.64
  Class::Accessor::Fast: 0.22
  Class::Data::Accessor: 0.02
  DBIx::Class: 0.05006
  UNIVERSAL::require: 0.1
recommends:
  DBIx::Class::Schema::Loader: 0.02003
build_requires:
  Test::More: 0.32
provides:
  Catalyst::Helper::Model::DBIC::Schema:
    file: lib/Catalyst/Helper/Model/DBIC/Schema.pm
  Catalyst::Helper::Model::DBIC::SchemaLoader:
    file: lib/Catalyst/Helper/Model/DBIC/SchemaLoader.pm
  Catalyst::Model::DBIC::Schema:
    file: lib/Catalyst/Model/DBIC/Schema.pm
    version: 0.08
generated_by: Module::Build version 0.2611
